---
- hosts: firewall
  gather_facts: false
  connection: local

  vars:
    rule_name: 'Survey Rule'
    source_zone: 'trust'
    source_ip: 'any'
    destination_zone: 'untrust'
    destination_ip: 'any'
    application:
      - 'any'
    service:
      - 'application-default'

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Create security rule via extra_vars
      panos_security_rule:
        provider: '{{ provider }}'
        rule_name: '{{ rule_name }}'
        source_zone: '{{ source_zone }}'
        destination_zone: '{{ destination_zone }}'
        source_ip: '{{ source_ip }}'
        destination_ip: '{{ destination_ip }}'
        application: '{{ application }}'
        service: '{{ service }}'
        action: 'allow'
        tag_name: '{{ tag|default([]) }}'
        commit: False
