---
# upgrade_single.yml - PAN-OS single firewall upgrade playbook.
#
# Description
# ===========
#
# Upgrades a single PAN-OS device to the specified version.  Upgrade must be a single step (i.e. 8.1.7 to 8.1.12).
# For major version upgrades requiring a base image to be downloaded to the device prior to performing the upgrade,
# see the 'download_panos_image.yml' playbook.
#
# Connection details for the device must be specified in the 'device' variable.
#
# Modules Used
# ============
#
# panos_op - https://ansible-pan.readthedocs.io/en/latest/modules/panos_op_module.html
#
# Usage
# =====
#
# Required variables:
#
#   target: Target PAN-OS device, as named in the inventory.  See `host_vars/firewall.yml` for sample 
#           definition of host variables.
#
#   target_version: Target version for upgrade.
#
# See the VARS section of the playbook for additional customization options.
#
# Default run (maintenance release upgrade):
#
#  $ ansible-playbook -i inventory upgrade_ha.yml --extra-vars "target=firewall target_version=9.0.3-h3"

- hosts: '{{ target | default("firewall") }}'
  connection: local

  vars:
    # backup_config - Create a backup of the currently running config.
    backup_config: true

    # backup_filename - Filename for running config backup.
    backup_filename: 'ansible-backup-{{ ansible_date_time.date }}.xml'

  roles:
    - PaloAltoNetworks.paloaltonetworks

  tasks:
    - name: Backup device config
      panos_op:
        provider: '{{ device }}'
        cmd: 'save config to {{ backup_filename }}'
      when: backup_config|bool

    - name: Install target PAN-OS version
      panos_software:
        provider: '{{ device }}'
        version: '{{ target_version }}'
        restart: true

    - pause:
        seconds: 30

    - name: Check to see if device is ready
      panos_op:
        provider: '{{ device }}'
        cmd: 'show chassis-ready'
      changed_when: false
      register: result
      until: result is not failed and (result.stdout | from_json).response.result == 'yes'
      retries: 30
      delay: 60
